# Generated by Django 5.2 on 2025-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_alter_district_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
