# Generated by Django 5.2 on 2026-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0020_alter_pharmacy_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
